runtime: python310

# [START handlers]
handlers:
- url: /.*
  script: auto
# [END handlers]

env_variables:
  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: '<YOUR_APPENGINE_APP_ID_HERE>'
